variables:
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - build-staging
  - master
  - staging
  - production

include:
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/build-staging.gitlab-ci.yml
  - local: .gitlab/ci/staging.gitlab-ci.yml
  - local: .gitlab/ci/master.gitlab-ci.yml
  - local: .gitlab/ci/production.gitlab-ci.yml
