FROM node:14-bullseye-slim
WORKDIR /usr/src/app

COPY . .

RUN yarn install
RUN yarn build-staging

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["yarn", "prod"]
