export const buildingSchemaForExportToCsv = [
  { prop: 'address', title: 'Address', defaultValue: '' },
  { prop: 'buildingConnectionDate', title: 'Connection date', defaultValue: '' },
  { prop: 'buildingName', title: 'Building name', defaultValue: '' },
  { prop: 'cadastralIdentifier', title: 'Cadastral identifier', defaultValue: '' },
  { prop: 'status', title: 'Footprint', defaultValue: 'N/A' },
  { prop: 'uniqueCode', title: 'Unique code', defaultValue: '' },
  { prop: 'addressComponents.isMaster', title: 'Master', defaultValue: '' },
  { prop: 'addressComponents.isSlave', title: 'Slave', defaultValue: '' },
  { prop: 'addressComponents.buildingConnectionCosts', title: 'Building connection costs', defaultValue: 0 },
  { prop: 'addressComponents.internalInstallationCosts', title: 'Internal installation costs', defaultValue: 0 },
  { prop: 'numberOfDwellings', title: 'Number of dwellings', defaultValue: 0 },
  { prop: 'numberOfLevels', title: 'Number of levels', defaultValue: 0 },
  { prop: 'customerInstallApprovalRequired', title: 'Customer install approval required', defaultValue: false },
  { prop: 'inductionRequired', title: 'Induction required', defaultValue: false },
  { prop: 'avgFloorHeight', title: 'Avg floor height', defaultValue: 0 },
  { prop: 'estimatedServiceDeliveryTime', title: 'Estimated service delivery time', defaultValue: '' },
  { prop: 'parkingAvailability', title: 'Parking availability', defaultValue: '' },
  { prop: 'addressComponents.buildingClass', title: 'Building class', defaultValue: '' },
  { prop: 'addressComponents.buildingType', title: 'Building type', defaultValue: '' },
  { prop: 'addressComponents.buildingCategory', title: 'Established or new', defaultValue: '' },
  { prop: 'access.toRiser', title: 'Access to riser', defaultValue: '' },
  { prop: 'access.toMDF', title: 'Access to MDF', defaultValue: '' },
  { prop: 'access.toBuilding', title: 'Access to building', defaultValue: '' },
  { prop: 'access.toCarPark', title: 'Access to car park', defaultValue: '' },
  { prop: 'access.installationAccessTimes.from', title: 'Access time from', defaultValue: '' },
  { prop: 'access.installationAccessTimes.to', title: 'Access time to', defaultValue: '' },
  { prop: 'corporation.corporationName', title: 'Corporation name', defaultValue: '' },
  { prop: 'corporation.contactPerson', title: 'Corporation contact person', defaultValue: '' },
  { prop: 'corporation.corporationPhoneWork', title: 'Corporation phone work', defaultValue: '' },
  { prop: 'corporation.corporationPhoneMobile', title: 'Corporation phone mobile', defaultValue: '' },
  { prop: 'corporation.corporationEmailPrimary', title: 'Corporation email primary', defaultValue: '' },
  { prop: 'corporation.corporationEmailAlternative', title: 'Corporation email alternative', defaultValue: '' },
  { prop: 'corporation.headOfficeAddress', title: 'Owners corporation head office address', defaultValue: '' },
  { prop: 'corporation.managementPSNumber', title: 'Owners corporation management PS number', defaultValue: '' },
  { prop: 'owner.corporationName', title: 'Owners corporation name', defaultValue: '' },
  { prop: 'owner.contactPerson', title: 'Owners corporation contact person', defaultValue: '' },
  { prop: 'owner.corporationPhoneWork', title: 'Owners corporation phone work', defaultValue: '' },
  { prop: 'owner.corporationPhoneMobile', title: 'Owners corporation phone mob', defaultValue: '' },
  { prop: 'owner.corporationEmailPrimary', title: 'Owners corporation email primary', defaultValue: '' },
  { prop: 'owner.corporationEmailAlternative', title: 'Owners corporation email alternative', defaultValue: '' },
  { prop: 'concierge.conciergeName', title: 'Concierge name', defaultValue: '' },
  { prop: 'concierge.conciergePhoneWork', title: 'Concierge phone work', defaultValue: '' },
  { prop: 'concierge.phoneMobile', title: 'Concierge phone mob', defaultValue: '' },
  { prop: 'concierge.emailPrimary', title: 'Concierge email (primary)', defaultValue: '' },
  { prop: 'concierge.emailAlternative', title: 'Concierge email (alternative)', defaultValue: '' },
  { prop: 'infrastructure.backbone.planned', title: 'Backbone planned', defaultValue: false },
  { prop: 'infrastructure.backbone.installed', title: 'Backbone installed', defaultValue: false },
  { prop: 'infrastructure.leadIn.planned', title: 'Lead in planned', defaultValue: false },
  { prop: 'infrastructure.leadIn.installed', title: 'Lead in installed', defaultValue: false },
  { prop: 'infrastructure.customerAccessCabling.planned', title: 'Customer access cabling planned', defaultValue: false },
  { prop: 'infrastructure.customerAccessCabling.installed', title: 'Customer access cabling installed', defaultValue: false },
  { prop: 'infrastructure.gPOinMDF.planned', title: 'GPO in MDF planned', defaultValue: false },
  { prop: 'infrastructure.gPOinMDF.installed', title: 'GPO in MDF installed', defaultValue: false },
  { prop: 'infrastructure.gPOinMDF.exist', title: 'GPO in MDF exist', defaultValue: false },
  { prop: 'infrastructure.uPSinMDF.planned', title: 'UPS in MDF planned', defaultValue: false },
  { prop: 'infrastructure.uPSinMDF.installed', title: 'UPS in MDF installed', defaultValue: false },
  { prop: 'infrastructure.gPOinRisers.planned', title: 'GPO in risers planned', defaultValue: false },
  { prop: 'infrastructure.gPOinRisers.installed', title: 'GPO in risers installed', defaultValue: false },
  { prop: 'infrastructure.gPOinRisers.exist', title: 'GPO in risers exist', defaultValue: false },
  { prop: 'infrastructure.uPSinRisers.planned', title: 'UPS in risers planned', defaultValue: false },
  { prop: 'infrastructure.uPSinRisers.installed', title: 'UPS in risers installed', defaultValue: false },
  { prop: 'infrastructure.type', title: 'Infrastructure type', defaultValue: '' },
  { prop: 'management.managerName', title: 'Building manager name', defaultValue: '' },
  { prop: 'management.managerPhoneWork', title: 'Building manager phone work', defaultValue: '' },
  { prop: 'management.phoneMobile', title: 'Building manager phone mob', defaultValue: '' },
  { prop: 'management.emailPrimary', title: 'Building manager email primary', defaultValue: '' },
  { prop: 'management.emailAlternative', title: 'Building manager email alternative', defaultValue: '' },
  { prop: 'marketing.foyer', title: 'Foyer', defaultValue: false },
  { prop: 'marketing.foyerDetails', title: 'Foyer details', defaultValue: '' },
  { prop: 'marketing.lift', title: 'Lift', defaultValue: false },
  { prop: 'marketing.liftDetails', title: 'Lift details', defaultValue: '' },
  { prop: 'marketing.other', title: 'Other marketing', defaultValue: '' }
]
