deploy:
  stage: production
  image: dtzar/helm-kubectl
  before_script:
    - sed -i "s~<VERSION>~${CI_COMMIT_SHA}~g" .helm/Chart.yaml
  script:
    - helm upgrade dgtek-admin-dash .helm --namespace dgtek-admin-dash --install --values .helm/values.prod.yaml
  environment:
    name: production
  rules:
    - if: $CI_COMMIT_TAG
